# Generated by Django 5.1.2 on 2024-11-15 09:53

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(default=transactions.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('issued', 'issued'), ('returned', 'returned')], max_length=10)),
                ('fee_charged', models.FloatField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
