# Generated by Django 5.1.2 on 2024-11-09 12:54

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(default=books.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=20)),
                ('isbn13', models.CharField(max_length=20)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('rent_fee', models.FloatField()),
                ('publication_date', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=1000)),
            ],
        ),
    ]
